# Generated by Django 2.1.7 on 2019-02-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cred',
            name='itype',
            field=models.PositiveIntegerField(choices=[(0, 'Raw Item'), (1, 'Mysql'), (2, 'Web')], default=0, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='credaudit',
            name='audittype',
            field=models.CharField(choices=[('A', 'Added'), ('C', 'Changed'), ('M', 'Only Metadata Changed'), ('V', 'Only Details Viewed'), ('X', 'Exported'), ('D', 'Deleted'), ('S', 'Scheduled For Change'), ('P', 'Password Viewed'), ('L', 'Login To')], max_length=1),
        ),
    ]
