# Generated by Django 2.1.7 on 2019-02-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0002_auto_20190225_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='cred',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='cred',
            name='ip_port',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='IP Port'),
        ),
        migrations.AlterField(
            model_name='cred',
            name='itype',
            field=models.PositiveIntegerField(choices=[(0, 'Normal'), (1, 'Mysql'), (2, 'GameBackend')], default=0, verbose_name='Type'),
        ),
    ]
